#!/bin/bash

# When creating filesystems with zfs, you may run into the problem that you want to re-use a zpool name from a previous, perhaps not longer existing, partition or disc,
# but you cannot. This is becasue of metadata. If you want to erase metadata on a partition  (e.g., /dev/nvme0n1pX or /dev/sdaY, 'X' and 'Y' representing your partition number)
# the following script may help you with this
list_devices() {
    echo "Available devices:"
    lsblk -o NAME,SIZE,TYPE,MOUNTPOINT
}

erase_disc_metadata() {
    echo "Erasing metadata from $1..."
    dd if=/dev/zero of="$1" seek=$(($(blockdev --getsz "$1") - ( ( 256 * 1024 * 2)  / $(blockdev --getpbsz "$1") ) ))
}

echo "WARNING: This script will erase disk metadata and can lead to data loss."
list_devices
read -p "Enter the device name (e.g., /dev/sda, /dev/nvme0n1): " device

if [ -b "$device" ]; then
    read -p "Are you sure you want to erase metadata from $device? (yes/no): " confirmation
    if [ "$confirmation" == "yes" ]; then
        erase_disc_metadata "$device"
        echo "Metadata erased from $device."
    else
        echo "Operation canceled."
    fi
else
    echo "Invalid device name."
fi
